variable "project_name" {
  description = "Project name used for resource naming and tagging across all files"
  type        = string
  default     = "three-tier-ha-aws"
}

variable "environment" {
  description = "Environment name (e.g. dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "ap-south-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC. Public/private-app/private-db subnet CIDRs are derived from this with cidrsubnet() in vpc.tf."
  type        = string
  default     = "10.0.0.0/16"
}

variable "azs" {
  description = "Availability zones to spread the 3 tiers of subnets across. Exactly 2 is the tested/expected size for this design."
  type        = list(string)
  default     = ["ap-south-1a", "ap-south-1b"]
}

variable "notification_email" {
  description = "Email address to receive CloudWatch alarm notifications via SNS. AWS sends a confirmation link here after apply."
  type        = string
}

variable "app_port" {
  description = "Port the application listens on (target group + app security group)"
  type        = number
  default     = 8080
}

variable "db_port" {
  description = "Port the database listens on"
  type        = number
  default     = 3306
}

variable "instance_type" {
  description = "EC2 instance type for the Auto Scaling Group"
  type        = string
  default     = "t3.micro"
}

variable "db_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t3.micro"
}

variable "multi_az" {
  description = "Whether RDS runs Multi-AZ. Note: Multi-AZ is NOT covered by AWS free tier — see docs/cost-estimate.md."
  type        = bool
  default     = true
}

variable "db_name" {
  description = "Initial database name created on the RDS instance"
  type        = string
  default     = "appdb"
}

variable "db_username" {
  description = "Master username for the RDS instance. The password is generated by Terraform (random_password) and never set here."
  type        = string
  default     = "appadmin"
}

variable "asg_min_size" {
  description = "Minimum number of instances in the Auto Scaling Group"
  type        = number
  default     = 2
}

variable "asg_max_size" {
  description = "Maximum number of instances in the Auto Scaling Group"
  type        = number
  default     = 4
}

variable "asg_desired_capacity" {
  description = "Desired number of instances in the Auto Scaling Group"
  type        = number
  default     = 2
}