apiVersion: v1

kind: Pod

metadata:
  name: nginx-secret-pod

spec:
  containers:
    - name: nginx
      image: nginx

      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: username

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: password